"$schema" = "./node_modules/wrangler/config-schema.json"
# Top-level configuration
name = "jeanmachine"
main = ".svelte-kit/cloudflare/_worker.js"
compatibility_date = "2026-02-19"
compatibility_flags = ["nodejs_compat"]

[assets]
binding = "ASSETS"
directory = ".svelte-kit/cloudflare"

[[routes]]
pattern = "jeanmachine.dev/*"
zone_name = "jeanmachine.dev"

[[routes]]
pattern = "jeanmachine.dev"
zone_name = "jeanmachine.dev"
