"$schema" = "./node_modules/wrangler/config-schema.json"
# Top-level configuration
name = "jeanmachine"
main = "./.cloudflare/worker.js"
compatability_date = "2026-02-19"

[site]
bucket = "./.svelte-kit/cloudflare"
