"$schema" = "./node_modules/wrangler/config-schema.json"
# Top-level configuration
name = "jeanmachine"
main = "./.cloudflare/worker.js"
compatibility_date = "2026-02-19"
compatibility_flags = ["nodejs_compat"]

[site]
bucket = "./.svelte-kit/cloudflare"
